### ISSUE TITLE
Stuck in bootloop

### ISSUE THREAD

**Issue by elmagow** [chris1111/D-LinkUtility-Package#2]
Hello,

I’ve installed the software and rebooted as the instruction stated and now I’m stuck in a bootloop.

Can I uninstall / delete the files from recovery mode to revert the changes?

Ps: I have real mac, and dumb me didn't think about making a time machine save before 🥲

Regards

**Comment by chris1111** [comment]
it is practically impossible what happens and it would surprise me that it is relate to this utility because it is already tested on a mac book pro late 2013. It is not a kext in Library Extensions which prevents macOS booting especially with [kmutil repair permissions.](https://developer.apple.com/documentation/apple-silicon/installing-a-custom-kernel-extension )

**Comment by elmagow** [comment]
Would you have a solution for me to fix the bootloop? The strange thing is that it is booting on snap disk and not the normal ssd

**Comment by elmagow** [comment]
I managed to reinstall osx and its starting again.
Any clue on why I have an EFI disk and my main ssd rename to snap-disk?

**Comment by chris1111** [comment]
> I managed to reinstall osx and its starting again.
> Any clue on why I have an EFI disk and my main ssd rename to snap-disk?


https://github.com/chris1111/D-LinkUtility-Package/issues/2#issuecomment-876511022

**Comment by chris1111** [comment]
All mac have EFI Partition
you can rename the disk thats not a problem
